
-- ZAD 1
-- 1
CREATE TABLE infs_dunajskim.CLIENT SELECT * FROM company_2025.CLIENT;
CREATE TABLE infs_dunajskim.ORDER SELECT * FROM company_2025.ORDER;
CREATE TABLE infs_dunajskim.EMPLOYEE SELECT * FROM company_2025.EMPLOYEE;
-- 2
SELECT * FROM `ORDER`;
-- 3
SELECT * FROM `ORDER` WHERE ORDER_STATUS=5;
-- 4
SELECT ORDER_ID, ORDER_STATUS FROM `ORDER` WHERE CLIENT_ID IN (1,3,5);

-- ZAD 2
-- 1
SELECT * FROM `EMPLOYEE` WHERE FIRST_NAME='Agnieszka' AND pensja=3900;
-- 2
 SELECT FIRST_NAME, LAST_NAME FROM `EMPLOYEE` WHERE pensja BETWEEN 5000 AND 7000;
 -- 3
 SELECT FULL_NAME FROM `CLIENT` WHERE SHORT_NAME LIKE 'eco%' AND IS_COMPANY = 1;
 -- ZAD 3 
 -- 1
 SELECT * FROM `ORDER` WHERE ORDER_DATE LIKE '%-06-%' OR ORDER_DATE LIKE '%-07-%';
 -- 2 
SELECT * FROM `CLIENT` WHERE TAX_IDENTIFIER IS NOT NULL ORDER BY `SHORT_NAME` ASC;
-- 3
SELECT * FROM EMPLOYEE ORDER BY BIRTH_DATE ASC LIMIT 5;

-- ZAD 4
-- 1
 SELECT DISTINCT FIRST_NAME FROM EMPLOYEE;
 -- 2
 SELECT CONCAT(FIRST_NAME, ' - ', LAST_NAME) FROM EMPLOYEE;
 -- 3
 SELECT LAST_NAME, pensja FROM EMPLOYEE WHERE YEAR(DATE_OF_EMPLOYMENT) BETWEEN 2010 AND 2014 ;

 -- ZAD 5
 --1 
 ELECT FIRST_NAME, LAST_NAME, pensja, (pensja-pensja*0.23) AS netto, (pensja*0.23) AS podatek FROM EMPLOYEE;
-- 2
SELECT * FROM CLIENT WHERE TAX_IDENTIFIER IS NULL;
--3 
SELECT SHORT_NAME FROM CLIENT WHERE FULL_NAME LIKE 'K%' OR FULL_NAME LIKE '%ski' ORDER BY SHORT_NAME DESC;