-- ZAD 1
-- 1
SELECT AVG(pensja) FROM EMPLOYEE;
-- 2
SELECT JOB_POSITION_ID, AVG(pensja), COUNT(EMPLOYEE_NAME) FROM EMPLOYEE GROUP BY JOB_POSITION_ID;
-- 3
 SELECT DEPARTMENT_ID, AVG(2025-YEAR(BIRTH_DATE)) FROM EMPLOYEE GROUP BY DEPARTMENT_ID;

 -- ZADANIE 2
 --1 
 SELECT DEPARTMENT_ID, SUM(pensja) AS suma FROM EMPLOYEE GROUP BY DEPARTMENT_ID ORDER BY suma DESC;
 --2
SELECT JOB_POSITION.POSITION_NAME, AVG(pensja) FROM EMPLOYEE JOIN JOB_POSITION ON EMPLOYEE.JOB_POSITION_ID=JOB_POSITION.JOB_POSITION_ID GROUP BY JOB_POSITION.POSITION_NAME HAVING COUNT(EMPLOYEE_NAME) >= 3 AND AVG(pensja)>3000;
 --3
 SELECT DEPARTMENT_ID, COUNT(DISTINCT pensja) FROM EMPLOYEE GROUP BY DEPARTMENT_ID HAVING COUNT(EMPLOYEE_NAME)>4 ORDER BY COUNT(DISTINCT pensja) ASC;

-- ZADANIE 3
-- 1
 CREATE TABLE infs_dunajskim.DEPARTMENT SELECT * FROM company_2025.DEPARTMENT;
  CREATE TABLE infs_dunajskim.JOB_POSITION SELECT * FROM company_2025.JOB_POSITION;
-- 2
SELECT DEPARTMENT.DEPARTMENT_NAME, COUNT(EMPLOYEE.EMPLOYEE_NAME) FROM EMPLOYEE JOIN DEPARTMENT ON EMPLOYEE.DEPARTMENT_ID=DEPARTMENT.DEPARTMENT_ID GROUP BY DEPARTMENT.DEPARTMENT_NAME;
-- 3
SELECT DEPARTMENT.DEPARTMENT_NAME, GROUP_CONCAT(EMPLOYEE.FIRST_NAME, ' ', EMPLOYEE.LAST_NAME SEPARATOR ', ') AS pracownicy FROM EMPLOYEE JOIN DEPARTMENT ON EMPLOYEE.DEPARTMENT_ID=DEPARTMENT.DEPARTMENT_ID GROUP BY DEPARTMENT.DEPARTMENT_NAME;

--ZADANIE 4
-- 1
SELECT EMPLOYEE.LAST_NAME, DEPARTMENT.DEPARTMENT_NAME FROM EMPLOYEE JOIN DEPARTMENT ON EMPLOYEE.DEPARTMENT_ID=DEPARTMENT.DEPARTMENT_ID WHERE YEAR(BIRTH_DATE) BETWEEN 1990 AND 1999;
-- 2
SELECT EMPLOYEE.FIRST_NAME, EMPLOYEE.LAST_NAME FROM EMPLOYEE JOIN JOB_POSITION ON EMPLOYEE.JOB_POSITION_ID=JOB_POSITION.JOB_POSITION_ID WHERE JOB_POSITION.POSITION_NAME LIKE 'Magazynier' ORDER BY EMPLOYEE.BIRTH_DATE DESC LIMIT 5;
-- 3
SELECT CONCAT(c1.SHORT_NAME, ' - ', c2.SHORT_NAME) FROM CLIENT c1 JOIN CLIENT c2 ON c1.CLIENT_ID = c2.CLIENT_ID + 5 ORDER BY c1.CLIENT_ID;

-- ZADANIE 5 
-- 1 
 SELECT JOB_POSITION.POSITION_NAME, AVG(EMPLOYEE.pensja)  FROM EMPLOYEE  JOIN JOB_POSITION ON JOB_POSITION.JOB_POSITION_ID = EMPLOYEE.JOB_POSITION_ID JOIN DEPARTMENT ON DEPARTMENT.DEPARTMENT_ID = EMPLOYEE.DEPARTMENT_ID  WHERE DEPARTMENT.DEPARTMENT_NAME NOT LIKE 'IT' AND DEPARTMENT.DEPARTMENT_NAME NOT LIKE 'HR' GROUP BY JOB_POSITION.POSITION_NAME HAVING COUNT(EMPLOYEE.EMPLOYEE_NAME)>3;
 -- 2
 select j.POSITION_NAME, GROUP_CONCAT(e.FIRST_NAME, ', ', e.LAST_NAME, ', ', e.BIRTH_DATE, ', ', d.DEPARTMENT_NAME SEPARATOR ', ') AS costam from JOB_POSITION j join EMPLOYEE e on e.JOB_POSITION_ID = j.JOB_POSITION_ID join DEPARTMENT d on d.DEPARTMENT_ID = e.DEPARTMENT_ID where e.BIRTH_DATE = (select max(tmp_e.BIRTH_DATE) from EMPLOYEE tmp_e where tmp_e.JOB_POSITION_ID = e.JOB_POSITION_ID) or e.BIRTH_DATE = (select min(tmp_e.BIRTH_DATE) from EMPLOYEE tmp_e where tmp_e.JOB_POSITION_ID = e.JOB_POSITION_ID) GROUP BY j.POSITION_NAME;